#!/usr/bin/perl

# Copyright (c) 2019 Todd T. Fries <todd@fries.net>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use strict;
use warnings;

use Bot::Framework;
use Command::FAQ;
use Command::debug;
use Command::i;
use Command::set;
use Command::q;
use Command::Usage;
use Data::Dumper;
use Getopt::Std;
use ReadConf;

our $opt_c = $ENV{'HOME'}."/.dbot-stfcostats.conf";
our $opt_n;

getopt('c:n');

my $r = ReadConf->new();
my $config = $r->readconf($opt_c);

my $bot = Bot::Framework->new(%{$config});

Command::FAQ->new('bot' => $bot);
Command::debug->new('bot' => $bot);
Command::i->new('bot' => $bot);
Command::set->new('bot' => $bot);
Command::q->new('bot' => $bot);
Command::Usage->new('bot' => $bot);

if (defined($opt_n)) {
	print "Parsing bits tested ok, exiting\n";
	exit(0);
}

print "Starting Bot\n";

$bot->start();

print "Ending Bot\n";
